### ISSUE TITLE
No compatible version found: cylon-firmata@'undefined0.23.0'

### ISSUE THREAD

**Issue by helloCaller** [hybridgroup/cylon#320] opened 2015-11-18 21:33 UTC
Hi there, I'm trying to set up the use of arduino but when trying to do the "npm install cylon-firmata cylon-gpio cylon-i2c " in terminal, I get the message below. I'm not sure which package version is being requested that might not exist. Any help, or point in the right direction would be much appreciated.
Thank you.

npm WARN package.json @1.0.0 No README data
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "cylon-firmata" "cylon-gpio" "cylon-i2c"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: cylon-firmata@'undefined0.23.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.2.0","0.3.0","0.4.0","0.5.0","0.6.0","0.7.0","0.8.0","0.8.1","0.9.0","0.10.0","0.10.2","0.11.0","0.11.1","0.12.0","0.13.0","0.13.1","0.14.0","0.15.0","0.16.0","0.17.0","0.17.1","0.17.2","0.18.0","0.19.0","0.20.0","0.21.0","0.22.0","0.23.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by deadprogram** [comment] 2015-11-19 02:06
I just tried on my machine with Node 4.2.2, and it worked for me:

```
$ node -v
v4.2.2
$ npm -v
2.14.7
$ npm install cylon-firmata cylon-gpio cylon-i2c
|
> serialport@2.0.5 install /home/ron/Development/cylonjs/cylon-example/node_modules/cylon-firmata/node_modules/firmata/node_modules/serialport
> node-pre-gyp install --fallback-to-build

[serialport] Success: "/home/ron/Development/cylonjs/cylon-example/node_modules/cylon-firmata/node_modules/firmata/node_modules/serialport/build/Release/node-v46-linux-x64/serialport.node" is installed via remote
cylon-i2c@0.23.0 node_modules/cylon-i2c
└── cylon@1.2.0

cylon-gpio@0.27.0 node_modules/cylon-gpio
└── cylon@1.2.0

cylon-firmata@0.23.0 node_modules/cylon-firmata
├── cylon@1.2.0
└── firmata@0.8.0 (browser-serialport@2.0.3, es6-shim@0.33.13, serialport@2.0.5)
```

Perhaps clean your node_modules directory, and try again?

**Comment by deadprogram** [comment] 2015-12-01 04:08
Hi, @helloCaller did you ever have a chance to retry your install? I was not able to reproduce your problem. Please let us know.

**Comment by helloCaller** [comment] 2015-12-01 04:31
I'm currently in a uni that (irritatingly) images our laptops, and in doing so restricts some permissions, causing issues with a global node installation. Did a local install and things are good. Thanks for the follow up.

**Comment by deadprogram** [comment] 2015-12-01 04:50
OK, glad it worked out. Closing.

**Closed by deadprogram** 2015-12-01 04:50 UTC
